# Site settings
title: PGP Public Keyserver
email: matt@mattrude.com
description: ""
url: "https://keyserver.mattrude.com"
name: "keyserver.mattrude.com"
baseurl: ""
destination: "/var/www/html"

owner_name: "Matt Rude"
owner_pgpkey: "0xc4909ee495b0761f"

# Analytics settings
google_analytics_id: UA-9532791-9

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- css/syntax.less
- css/site.less
- css/small.less

gems:
- jekyll-sitemap
- jekyll-less
#- jekyll-press
- jekyll-redirect-from
- jekyll-last-modified-at

jekyll-press:
  exclude: 'robots.txt, contact.txt, contact-ecc.txt' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options
